#! /bin/bash
cd $1 ## Data file
REALIZATION=$(ls)
for item in ${REALIZATION}
do
  cd ${item}
  echo "items = ${item}"
  DECAYRE=$(ls)
  for item2 in ${DECAYRE}
  do
    cd ${item2}
    HOMETMP=$(pwd)
    FILE_NAME=$(ls *.mat)
    ADD_OUT="flt_DNS"
    cd $2
    if [ -e ${item}]
    then
      #mkdir -p ${item}
      rm -rf $2/${item}/*
    else
      mkdir -p ${item}
     # rm -rf $2/${item}/*
    fi
  done
done
~
